[build]
command = "npm run build"
publish = "dist/"
functions = "functions/"

[[redirects]]
from = "/api/search"
to = "/.netlify/functions/search"
status=200
force = true

[dev]
command="vite"
targetPort=3000
framework="#custom"
